version: '2'
services:
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    ports:
     - "80:80"
  php:
    extends:
      file: docker-compose.base.yml
      service: php
    environment:
      APP_ENV: ${APP_ENV}
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-app
      MYSQL_USER: app-user
      MYSQL_PASSWORD: app-pass
networks:
  sdnet0:
    driver: "bridge"
    driver_opts:
      com.docker.network.bridge.name: br-sdnet0
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
